<?php

use Illuminate\Database\Seeder;

class FinanceiroBancoSeeder extends BaseSeedPublic
{
    public function run()
    {
        $bancos = [
                    0 => ['codigobanco' =>'001', 'descricao' => 'BANCO DO BRASIL S.A.'],
                    1 => ['codigobanco' =>'003', 'descricao' => 'BANCO DA AMAZONIA S.A.'],
                    2 => ['codigobanco' =>'004', 'descricao' => 'BANCO DO NORDESTE DO BRASIL S.A.'],
                    3 => ['codigobanco' =>'021', 'descricao' => 'BANESTES S.A BANCO DO ESTADO DO ESPIRITO SANTO'],
                    4 => ['codigobanco' =>'024', 'descricao' => 'BANCO DE PERNAMBUCO S.A.-BANDEPE'],
                    5 => ['codigobanco' =>'025', 'descricao' => 'BANCO ALFA S/A'],
                    6 => ['codigobanco' =>'027', 'descricao' => 'BANCO DO ESTADO DE SANTA CATARINA S.A.'],
                    7 => ['codigobanco' =>'029', 'descricao' => 'BANCO BANERJ S.A.'],
                    8 => ['codigobanco' =>'031', 'descricao' => 'BANCO BEG S.A.'],
                    9 => ['codigobanco' =>'033', 'descricao' => 'BANCO SANTANDER S.A.'],
                    10 => ['codigobanco' =>'034', 'descricao' => 'BANCO DO ESTADO DO AMAZONAS S.A.'],
                    11 => ['codigobanco' =>'036', 'descricao' => 'BANCO BRADESCO BBI S.A.'],
                    12 => ['codigobanco' =>'037', 'descricao' => 'BANCO DO ESTADO DO PARA S.A.'],
                    13 => ['codigobanco' =>'038', 'descricao' => 'BANCO BANESTADO S.A.'],
                    14 => ['codigobanco' =>'039', 'descricao' => 'BANCO DO ESTADO DO PIAUI S.A. - BEP'],
                    15 => ['codigobanco' =>'040', 'descricao' => 'BANCO CARGILL S.A'],
                    16 => ['codigobanco' =>'041', 'descricao' => 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.'],
                    17 => ['codigobanco' =>'044', 'descricao' => 'BANCO BVA SA'],
                    18 => ['codigobanco' =>'045', 'descricao' => 'BANCO OPPORTUNITY S.A.'],
                    19 => ['codigobanco' =>'047', 'descricao' => 'BANCO DO ESTADO DE SERGIPE S.A.'],
                    20 => ['codigobanco' =>'062', 'descricao' => 'HIPERCARD BANCO MÚLTIPLO S.A'],
                    21 => ['codigobanco' =>'063', 'descricao' => 'BANCO IBI S.A - BANCO MULTIPLO'],
                    22 => ['codigobanco' =>'065', 'descricao' => 'LEMON BANK BANCO MÚLTIPLO S..A'],
                    23 => ['codigobanco' =>'066', 'descricao' => 'BANCO MORGAN STANLEY S.A'],
                    24 => ['codigobanco' =>'069', 'descricao' => 'BPN BRASIL BANCO MÚLTIPLO S.A.'],
                    25 => ['codigobanco' =>'070', 'descricao' => 'BRB - BANCO DE BRASILIA S.A.'],
                    26 => ['codigobanco' =>'072', 'descricao' => 'BANCO RURAL MAIS S.A. '],
                    27 => ['codigobanco' =>'073', 'descricao' => 'BB BANCO POPULAR DO BRASL S.A. '],
                    28 => ['codigobanco' =>'074', 'descricao' => 'BANCO J.SAFRA S.A. '],
                    29 => ['codigobanco' =>'075', 'descricao' => 'BANCO CR2 S.A. '],
                    30 => ['codigobanco' =>'076', 'descricao' => 'BANCO KDB DO BRASIL S.A. '],
                    31 => ['codigobanco' =>'096', 'descricao' => 'BANCO BM&F DE SERVIÇOS DE LIQUIDAÇÃO E CUSTÓDIA S.A.'],
                    32 => ['codigobanco' =>'116', 'descricao' => 'BANCO ÚNICO S.A.'],
                    33 => ['codigobanco' =>'151', 'descricao' => 'BANCO NOSSA CAIXA S.A'],
                    34 => ['codigobanco' =>'175', 'descricao' => 'BANCO FINASA S.A.'],
                    35 => ['codigobanco' =>'184', 'descricao' => 'BANCO ITAÚ - BBA S.A.'],
                    36 => ['codigobanco' =>'204', 'descricao' => 'BANCO BRADESCO CARTÕES S.A'],
                    37 => ['codigobanco' =>'208', 'descricao' => 'BANCO UBS PACTUAL S.A.'],
                    38 => ['codigobanco' =>'212', 'descricao' => 'BANCO MATONE S.A.'],
                    39 => ['codigobanco' =>'213', 'descricao' => 'BANCO ARBI S.A.'],
                    40 => ['codigobanco' =>'214', 'descricao' => 'BANCO DIBENS S.A.'],
                    41 => ['codigobanco' =>'215', 'descricao' => 'BANCO ACOMERCIAL E DE INVESTIMENTO SUDAMERIS S.A.'],
                    42 => ['codigobanco' =>'217', 'descricao' => 'BANCO JOHN DEERE S.A.'],
                    43 => ['codigobanco' =>'218', 'descricao' => 'BANCO BONSUCESSO S.A.'],
                    44 => ['codigobanco' =>'222', 'descricao' => 'BANCO CLAYON BRASIL S/A'],
                    45 => ['codigobanco' =>'224', 'descricao' => 'BANCO FIBRA S.A.'],
                    46 => ['codigobanco' =>'225', 'descricao' => 'BANCO BRASCAN S.A.'],
                    47 => ['codigobanco' =>'229', 'descricao' => 'BANCO CRUZEIRO DO SUL S.A.'],
                    48 => ['codigobanco' =>'230', 'descricao' => 'UNICARD BANCO MÚLTIPLO S.A.'],
                    49 => ['codigobanco' =>'233', 'descricao' => 'BANCO GE CAPITAL S.A'],
                    50 => ['codigobanco' =>'237', 'descricao' => 'BANCO BRADESCO S.A.'],
                    51 => ['codigobanco' =>'241', 'descricao' => 'BANCO CLASSICO S.A.'],
                    52 => ['codigobanco' =>'243', 'descricao' => 'BANCO MAXIMA S.A.'],
                    53 => ['codigobanco' =>'246', 'descricao' => 'BANCO ABC-BRASIL S.A.'],
                    54 => ['codigobanco' =>'248', 'descricao' => 'BANCO BOAVISTA INTERATLANTICO S.A. '],
                    55 => ['codigobanco' =>'249', 'descricao' => 'BANCO INVESTCRED UNIBANCO S.A.'],
                    56 => ['codigobanco' =>'250', 'descricao' => 'BANCO SCHAHIN'],
                    57 => ['codigobanco' =>'252', 'descricao' => 'BANCO FININVEST S.A.'],
                    58 => ['codigobanco' =>'254', 'descricao' => 'PARANÁ BANCO S.A.'],
                    59 => ['codigobanco' =>'263', 'descricao' => 'BANCO CACIQUE S.A.'],
                    60 => ['codigobanco' =>'265', 'descricao' => 'BANCO FATOR S.A.'],
                    61 => ['codigobanco' =>'266', 'descricao' => 'BANCO CEDULA S.A.'],
                    62 => ['codigobanco' =>'300', 'descricao' => 'BANCO DE LA NACION ARGENTINA'],
                    63 => ['codigobanco' =>'318', 'descricao' => 'BANCO BMG S.A.'],
                    64 => ['codigobanco' =>'320', 'descricao' => 'BANCO INDUSTRIAL E COMERCIAL S.A.'],
                    65 => ['codigobanco' =>'341', 'descricao' => 'BANCO ITAU S.A.'],
                    66 => ['codigobanco' =>'356', 'descricao' => 'BANCO ABN AMRO REAL S.A.'],
                    67 => ['codigobanco' =>'366', 'descricao' => 'BANCO SOCIETE GENERALE BRASIL S.A'],
                    68 => ['codigobanco' =>'370', 'descricao' => 'BANCO WESTLB DO BRASIL S.A.'],
                    69 => ['codigobanco' =>'376', 'descricao' => 'BANCO J.P. MORGAN S.A.'],
                    70 => ['codigobanco' =>'389', 'descricao' => 'BANCO MERCANTIL DO BRASIL S.A.'],
                    71 => ['codigobanco' =>'394', 'descricao' => 'BANCO BMC S.A.'],
                    72 => ['codigobanco' =>'399', 'descricao' => 'HSBC BANK BRASIL S.A.-BANCO MULTIPLO'],
                    73 => ['codigobanco' =>'409', 'descricao' => 'UNIBANCO - UNIAO DE BANCOS BRASILEIROS S.A.'],
                    74 => ['codigobanco' =>'412', 'descricao' => 'BANCO CAPITAL S.A.'],
                    75 => ['codigobanco' =>'422', 'descricao' => 'BANCO SAFRA S.A.'],
                    76 => ['codigobanco' =>'453', 'descricao' => 'BANCO RURAL S.A.'],
                    77 => ['codigobanco' =>'456', 'descricao' => 'BANCO DE TOKYO-MITSUBISHI UFJ BRASIL S.A.'],
                    78 => ['codigobanco' =>'464', 'descricao' => 'BANCO SUMITOMO MITSUI BRASILEIRO S.A.'],
                    79 => ['codigobanco' =>'477', 'descricao' => 'CITIBANK N.A.'],
                    80 => ['codigobanco' =>'479', 'descricao' => 'BANCO ITAUBANK S.A.'],
                    81 => ['codigobanco' =>'487', 'descricao' => 'DEUTSCHE BANK S. A. - BANCO ALEMAO'],
                    82 => ['codigobanco' =>'488', 'descricao' => 'JPMORGAN CHASE BANK, NATIONAL ASSOCIATION'],
                    83 => ['codigobanco' =>'492', 'descricao' => 'ING BANK N.V.'],
                    84 => ['codigobanco' =>'494', 'descricao' => 'BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY'],
                    85 => ['codigobanco' =>'495', 'descricao' => 'BANCO DE LA PROVINCIA DE BUENOS AIRES'],
                    86 => ['codigobanco' =>'505', 'descricao' => 'BANCO CREDIT SUISSE (BRASIL) S.A.'],
                    87 => ['codigobanco' =>'600', 'descricao' => 'BANCO LUSO BRASILEIRO S.A.'],
                    88 => ['codigobanco' =>'604', 'descricao' => 'BANCO INDUSTRIAL DO BRASIL S. A.'],
                    89 => ['codigobanco' =>'610', 'descricao' => 'BANCO VR S.A.'],
                    90 => ['codigobanco' =>'611', 'descricao' => 'BANCO PAULISTA S.A.'],
                    91 => ['codigobanco' =>'612', 'descricao' => 'BANCO GUANABARA S.A.'],
                    92 => ['codigobanco' =>'613', 'descricao' => 'BANCO PECUNIA S.A.'],
                    93 => ['codigobanco' =>'623', 'descricao' => 'BANCO PANAMERICANO S.A.'],
                    94 => ['codigobanco' =>'626', 'descricao' => 'BANCO FICSA S.A.'],
                    95 => ['codigobanco' =>'630', 'descricao' => 'BANCO INTERCAP S.A.'],
                    96 => ['codigobanco' =>'633', 'descricao' => 'BANCO RENDIMENTO S.A.'],
                    97 => ['codigobanco' =>'634', 'descricao' => 'BANCO TRIANGULO S.A.'],
                    98 => ['codigobanco' =>'637', 'descricao' => 'BANCO SOFISA S.A.'],
                    99 => ['codigobanco' =>'638', 'descricao' => 'BANCO PROSPER S.A.'],
                    100 => ['codigobanco' =>'641', 'descricao' => 'BANCO ALVORADA S.A'],
                    101 => ['codigobanco' =>'643', 'descricao' => 'BANCO PINE S.A.'],
                    102 => ['codigobanco' =>'652', 'descricao' => 'BANCO ITAÚ HOLDING FINANCEIRA S.A.'],
                    103 => ['codigobanco' =>'653', 'descricao' => 'BANCO INDUSVAL S.A.'],
                    104 => ['codigobanco' =>'654', 'descricao' => 'BANCO A.J. RENNER S.A.'],
                    105 => ['codigobanco' =>'655', 'descricao' => 'BANCO VOTORANTIM S.A.'],
                    106 => ['codigobanco' =>'707', 'descricao' => 'BANCO DAYCOVAL S.A.'],
                    107 => ['codigobanco' =>'719', 'descricao' => 'BANIF - BANCO INTERNACIONAL DO FUNCHAL (BRASIL), S.A.'],
                    108 => ['codigobanco' =>'721', 'descricao' => 'BANCO CREDIBEL S.A.'],
                    109 => ['codigobanco' =>'734', 'descricao' => 'BANCO GERDAU S.A.'],
                    110 => ['codigobanco' =>'735', 'descricao' => 'BANCO POTTENCIAL S.A.'],
                    111 => ['codigobanco' =>'738', 'descricao' => 'BANCO MORADA S.A.'],
                    112 => ['codigobanco' =>'739', 'descricao' => 'BANCO BGN S.A.'],
                    113 => ['codigobanco' =>'740', 'descricao' => 'BANCO BARCLAYS S.A.'],
                    114 => ['codigobanco' =>'741', 'descricao' => 'BANCO RIBEIRAO PRETO S.A.'],
                    115 => ['codigobanco' =>'743', 'descricao' => 'BANCO SEMEAR S.A.'],
                    116 => ['codigobanco' =>'744', 'descricao' => 'BANKBOSTON N.A.'],
                    117 => ['codigobanco' =>'745', 'descricao' => 'BANCO CITIBANK S.A.'],
                    118 => ['codigobanco' =>'746', 'descricao' => 'BANCO MODAL S.A.'],
                    119 => ['codigobanco' =>'747', 'descricao' => 'BANCO RABOBANK INTERNATIONAL BRASIL S.A.'],
                    120 => ['codigobanco' =>'748', 'descricao' => 'BANCO COOPERATIVO SICREDI S.A.'],
                    121 => ['codigobanco' =>'749', 'descricao' => 'BANCO SIMPLES S.A.'],
                    122 => ['codigobanco' =>'751', 'descricao' => 'DRESDNER BANK BRASIL S.A. BANCO MULTIPLO.'],
                    123 => ['codigobanco' =>'752', 'descricao' => 'BANCO BNP PARIBAS BRASIL S.A.'],
                    124 => ['codigobanco' =>'753', 'descricao' => 'BANCO COMERCIAL URUGUAI S.A.'],
                    125 => ['codigobanco' =>'756', 'descricao' => 'BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB'],
                    126 => ['codigobanco' =>'757', 'descricao' => 'BANCO KEB DO BRASIL S.A.']
        ];

        $this->obterConexao()->Table('financeirobanco')->insert($bancos);
    }
}