<?php

use Illuminate\Database\Seeder;

class FinanceiroContaGerencialSeeder extends Seeder
{
    public function run()
    {
        $contas = [
            0=> ['descricao' => 'ABATIMENTO',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 1],
            1=> ['descricao' => 'ÁGUA',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 8],
            2=> ['descricao' => 'ALUGUEL',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 3],
            3=> ['descricao' => 'ALUGUEL DE EQUIPAMENTOS',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 4],
            4=> ['descricao' => 'AMORTIZAÇÃO DE EMPRÉSTIMOS',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 5],
            5=> ['descricao' => 'ATIVOS E EQUIPAMENTOS PRÓPRIOS',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 4],
            6=> ['descricao' => 'BENEFÍCIOS SALARIAIS',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 6],
            7=> ['descricao' => 'BRINDES',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 7],
            8=> ['descricao' => 'COMBUSTÍVEL E PEDÁGIOS',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 4],
            9=> ['descricao' => 'COMISSÃO DE VENDAS',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 6],
            10=> ['descricao' => 'CONDOMÍNIO',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 3],
            11=> ['descricao' => 'CONTABILIDADE',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 4],
            12=> ['descricao' => 'DEVOLUÇÕES',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 1],
            13=> ['descricao' => 'EMBALAGEM',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 9],
            14=> ['descricao' => 'ENCARGOS SALARIAIS',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 6],
            15=> ['descricao' => 'EVENTOS',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 7],
            16=> ['descricao' => 'FRETE',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 4],
            17=> ['descricao' => 'HONORORIOS ADVOCATICIOS',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 4],
            18=> ['descricao' => 'IMPOSTOS',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 1],
            19=> ['descricao' => 'INTERNET',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 2,
	            'idfinanceirodemonstrativo' => 2],
            20=> ['descricao' => 'ENTRADAS',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 1,
	            'idfinanceirodemonstrativo' => 10],
            21=> ['descricao' => 'VENDAS',
	            'idempresa' => 1,
	            'idfinanceiromovimentotipo' => 1,
	            'idfinanceirodemonstrativo' => 10]
        ];

        DB::Table('financeirocontagerencial')->insert($contas);
    }
}
