<?php

use Illuminate\Database\Seeder;

class FiscalCFOPSeeder extends BaseSeedPublic
{
    public function run()
    {
        $cfops = [
                    1 => ['id' => '5101', 'descricao' => '5101 - Venda de produção do estabelecimento'],
                    2 => ['id' => '6101', 'descricao' => '6101 - Venda de produção do estabelecimento'],
                    3 => ['id' => '5949', 'descricao' => '5949 - Outra saída de mercadoria ou prestação de serviço não especificado'],
                    4 => ['id' => '6949', 'descricao' => '6949 - Outra saída de mercadoria ou prestação de serviço não especificado'],
                    5 => ['id' => '1101', 'descricao' => '1101 - Compra para industrialização'],
                    6 => ['id' => '1102', 'descricao' => '1102 - Compra para comercialização'],
                    7 => ['id' => '1111', 'descricao' => '1111 - Compra para industrialização de mercadoria recebida anteriormente em consignação industrial'],
                    8 => ['id' => '1113', 'descricao' => '1113 - Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil'],
                    9 => ['id' => '1116', 'descricao' => '1116 - Compra para industrialização originada de encomenda para recebimento futuro'],
                    10 => ['id' => '1117', 'descricao' => '1117 - Compra para comercialização originada de encomenda para recebimento futuro'],
                    11 => ['id' => '1118', 'descricao' => '1118 - Compra de mercadoria para comercialização ...edor remetente ao destinatário, em venda à ordem'],
                    12 => ['id' => '1120', 'descricao' => '1120 - Compra para industrialização, em venda à ordem, já recebida do vendedor remetente'],
                    13 => ['id' => '1121', 'descricao' => '1121 - Compra para comercialização, em venda à ordem, já recebida do vendedor remetente'],
                    14 => ['id' => '1122', 'descricao' => '1122 - Compra para industrialização em que a merc...or sem transitar pelo estabelecimento adquirente'],
                    15 => ['id' => '1124', 'descricao' => '1124 - Industrialização efetuada por outra empresa'],
                    16 => ['id' => '1125', 'descricao' => '1125 - Industrialização efetuada por outra empres...ou pelo estabelecimento adquirente da mercadoria'],
                    17 => ['id' => '1126', 'descricao' => '1126 - Compra para utilização na prestação de serviço'],
                    18 => ['id' => '1151', 'descricao' => '1151 - Transferência para industrialização'],
                    19 => ['id' => '1152', 'descricao' => '1152 - Transferência para comercialização'],
                    20 => ['id' => '1153', 'descricao' => '1153 - Transferência de energia elétrica para distribuição'],
                    21 => ['id' => '1154', 'descricao' => '1154 - Transferência para utilização na prestação de serviço'],
                    22 => ['id' => '1201', 'descricao' => '1201 - Devolução de venda de produção do estabelecimento'],
                    23 => ['id' => '1202', 'descricao' => '1202 - Devolução de venda de mercadoria adquirida ou recebida de terceiros'],
                    24 => ['id' => '1203', 'descricao' => '1203 - Devolução de venda de produção do estabele...Zona Franca de Manaus ou Áreas de Livre Comércio'],
                    25 => ['id' => '1204', 'descricao' => '1204 - Devolução de venda de mercadoria adquirida...Zona Franca de Manaus ou Áreas de Livre Comércio'],
                    26 => ['id' => '1205', 'descricao' => '1205 - Anulação de valor relativo à prestação de serviço de comunicação'],
                    27 => ['id' => '1206', 'descricao' => '1206 - Anulação de valor relativo à prestação de serviço de transporte'],
                    28 => ['id' => '1207', 'descricao' => '1207 - Anulação de valor relativo à venda de energia elétrica'],
                    29 => ['id' => '1208', 'descricao' => '1208 - Devolução de produção do estabelecimento, remetida em transferência'],
                    30 => ['id' => '1209', 'descricao' => '1209 - Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência'],
                    31 => ['id' => '1251', 'descricao' => '1251 - Compra de energia elétrica para distribuição ou comercialização'],
                    32 => ['id' => '1252', 'descricao' => '1252 - Compra de energia elétrica por estabelecimento industrial'],
                    33 => ['id' => '1253', 'descricao' => '1253 - Compra de energia elétrica por estabelecimento comercial'],
                    34 => ['id' => '1254', 'descricao' => '1254 - Compra de energia elétrica por estabelecimento prestador de serviço de transporte'],
                    35 => ['id' => '1255', 'descricao' => '1255 - Compra de energia elétrica por estabelecimento prestador de serviço de comunicação'],
                    36 => ['id' => '1256', 'descricao' => '1256 - Compra de energia elétrica por estabelecimento de produtor rural'],
                    37 => ['id' => '1257', 'descricao' => '1257 - Compra de energia elétrica para consumo por demanda contratada'],
                    38 => ['id' => '1301', 'descricao' => '1301 - Aquisição de serviço de comunicação para execução de serviço da mesma natureza'],
                    39 => ['id' => '1302', 'descricao' => '1302 - Aquisição de serviço de comunicação por estabelecimento industrial'],
                    40 => ['id' => '1303', 'descricao' => '1303 - Aquisição de serviço de comunicação por estabelecimento comercial'],
                    41 => ['id' => '1304', 'descricao' => '1304 - Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte'],
                    42 => ['id' => '1305', 'descricao' => '1305 - Aquisição de serviço de comunicação por es...geradora ou de distribuidora de energia elétrica'],
                    43 => ['id' => '1306', 'descricao' => '1306 - Aquisição de serviço de comunicação por estabelecimento de produtor rural'],
                    44 => ['id' => '1351', 'descricao' => '1351 - Aquisição de serviço de transporte para execução de serviço da mesma natureza'],
                    45 => ['id' => '1352', 'descricao' => '1352 - Aquisição de serviço de transporte por estabelecimento industrial'],
                    46 => ['id' => '1353', 'descricao' => '1353 - Aquisição de serviço de transporte por estabelecimento comercial'],
                    47 => ['id' => '1354', 'descricao' => '1354 - Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação'],
                    48 => ['id' => '1355', 'descricao' => '1355 - Aquisição de serviço de transporte por est...geradora ou de distribuidora de energia elétrica'],
                    49 => ['id' => '1356', 'descricao' => '1356 - Aquisição de serviço de transporte por estabelecimento de produtor rural'],
                    50 => ['id' => '1401', 'descricao' => '1401 - Compra para industrialização em operação c...ria sujeita ao regime de substituição tributária'],
                    51 => ['id' => '1403', 'descricao' => '1403 - Compra para comercialização em operação co...ria sujeita ao regime de substituição tributária'],
                    52 => ['id' => '1406', 'descricao' => '1406 - Compra de bem para o ativo imobilizado cuj...stá sujeita ao regime de substituição tributária'],
                    53 => ['id' => '1407', 'descricao' => '1407 - Compra de mercadoria para uso ou consumo c...stá sujeita ao regime de substituição tributária'],
                    54 => ['id' => '1408', 'descricao' => '1408 - Transferência para industrialização em ope...ria sujeita ao regime de substituição tributária'],
                    55 => ['id' => '1409', 'descricao' => '1409 - Transferência para comercialização em oper...ria sujeita ao regime de substituição tributária'],
                    56 => ['id' => '1410', 'descricao' => '1410 - Devolução de venda de produção do estabele...uto sujeito ao regime de substituição tributária'],
                    57 => ['id' => '1411', 'descricao' => '1411 - Devolução de venda de mercadoria adquirida...ria sujeita ao regime de substituição tributária'],
                    58 => ['id' => '1414', 'descricao' => '1414 - Retorno de produção do estabelecimento, re...uto sujeito ao regime de substituição tributária'],
                    59 => ['id' => '1415', 'descricao' => '1415 - Retorno de mercadoria adquirida ou recebid...ria sujeita ao regime de substituição tributária'],
                    60 => ['id' => '1451', 'descricao' => '1451 - Retorno de animal do estabelecimento produtor'],
                    61 => ['id' => '1452', 'descricao' => '1452 - Retorno de insumo não utilizado na produção'],
                    62 => ['id' => '1501', 'descricao' => '1501 - Entrada de mercadoria recebida com fim específico de exportação'],
                    63 => ['id' => '1503', 'descricao' => '1503 - Entrada decorrente de devolução de produto...co de exportação, de produção do estabelecimento'],
                    64 => ['id' => '1504', 'descricao' => '1504 - Entrada decorrente de devolução de mercado...e exportação, adquirida ou recebida de terceiros'],
                    65 => ['id' => '1551', 'descricao' => '1551 - Compra de bem para o ativo imobilizado'],
                    66 => ['id' => '1552', 'descricao' => '1552 - Transferência de bem do ativo imobilizado'],
                    67 => ['id' => '1553', 'descricao' => '1553 - Devolução de venda de bem do ativo imobilizado'],
                    68 => ['id' => '1554', 'descricao' => '1554 - Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento'],
                    69 => ['id' => '1555', 'descricao' => '1555 - Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento'],
                    70 => ['id' => '1556', 'descricao' => '1556 - Compra de material para uso ou consumo'],
                    71 => ['id' => '1557', 'descricao' => '1557 - Transferência de material para uso ou consumo'],
                    72 => ['id' => '1601', 'descricao' => '1601 - Recebimento, por transferência, de crédito de ICMS'],
                    73 => ['id' => '1602', 'descricao' => '1602 - Recebimento, por transferência, de saldo c...presa, para compensação de saldo devedor de ICMS'],
                    74 => ['id' => '1603', 'descricao' => '1603 - Ressarcimento de ICMS retido por substituição tributária'],
                    75 => ['id' => '1604', 'descricao' => '1604 - Lançamento do crédito relativo à compra de bem para o ativo imobilizado (Ajuste SINIEF 05/02)'],
                    76 => ['id' => '1605', 'descricao' => '1605 - Recebimento, por transferência, de saldo d...lecimento da mesma empresa (Ajuste SINIEF 03/04)'],
                    77 => ['id' => '1651', 'descricao' => '1651 - Compra de combustível ou lubrificante para industrialização subseqüente'],
                    78 => ['id' => '1652', 'descricao' => '1652 - Compra de combustível ou lubrificante para comercialização'],
                    79 => ['id' => '1653', 'descricao' => '1653 - Compra de combustível ou lubrificante por consumidor ou usuário final'],
                    80 => ['id' => '1658', 'descricao' => '1658 - Transferência de combustível e lubrificante para industrialização'],
                    81 => ['id' => '1659', 'descricao' => '1659 - Transferência de combustível e lubrificante para comercialização'],
                    82 => ['id' => '1660', 'descricao' => '1660 - Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente'],
                    83 => ['id' => '1661', 'descricao' => '1661 - Devolução de venda de combustível ou lubrificante destinado à comercialização'],
                    84 => ['id' => '1662', 'descricao' => '1662 - Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final'],
                    85 => ['id' => '1663', 'descricao' => '1663 - Entrada de combustível ou lubrificante para armazenagem'],
                    86 => ['id' => '1664', 'descricao' => '1664 - Retorno de combustível ou lubrificante remetido para armazenagem'],
                    87 => ['id' => '1901', 'descricao' => '1901 - Entrada para industrialização por encomenda'],
                    88 => ['id' => '1902', 'descricao' => '1902 - Retorno de mercadoria remetida para industrialização por encomenda'],
                    89 => ['id' => '1903', 'descricao' => '1903 - Entrada de mercadoria remetida para industrialização e não aplicada no referido processo'],
                    90 => ['id' => '1904', 'descricao' => '1904 - Retorno de remessa para venda fora do estabelecimento'],
                    91 => ['id' => '1905', 'descricao' => '1905 - Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral'],
                    92 => ['id' => '1906', 'descricao' => '1906 - Retorno de mercadoria remetida para depósito fechado ou armazém geral'],
                    93 => ['id' => '1907', 'descricao' => '1907 - Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral'],
                    94 => ['id' => '1908', 'descricao' => '1908 - Entrada de bem por conta de contrato de comodato'],
                    95 => ['id' => '1909', 'descricao' => '1909 - Retorno de bem remetido por conta de contrato de comodato'],
                    96 => ['id' => '1910', 'descricao' => '1910 - Entrada de bonificação, doação ou brinde'],
                    97 => ['id' => '1911', 'descricao' => '1911 - Entrada de amostra grátis'],
                    98 => ['id' => '1912', 'descricao' => '1912 - Entrada de mercadoria ou bem recebido para demonstração'],
                    99 => ['id' => '1913', 'descricao' => '1913 - Retorno de mercadoria ou bem remetido para demonstração'],
                    100 => ['id' => '1914', 'descricao' => '1914 - Retorno de mercadoria ou bem remetido para exposição ou feira'],
                    101 => ['id' => '1915', 'descricao' => '1915 - Entrada de mercadoria ou bem recebido para conserto ou reparo'],
                    102 => ['id' => '1916', 'descricao' => '1916 - Retorno de mercadoria ou bem remetido para conserto ou reparo'],
                    103 => ['id' => '1917', 'descricao' => '1917 - Entrada de mercadoria recebida em consignação mercantil ou industrial'],
                    104 => ['id' => '1918', 'descricao' => '1918 - Devolução de mercadoria remetida em consignação mercantil ou industrial'],
                    105 => ['id' => '1919', 'descricao' => '1919 - Devolução simbólica de mercadoria vendida ...riormente em consignação mercantil ou industrial'],
                    106 => ['id' => '1920', 'descricao' => '1920 - Entrada de vasilhame ou sacaria'],
                    107 => ['id' => '1921', 'descricao' => '1921 - Retorno de vasilhame ou sacaria'],
                    108 => ['id' => '1922', 'descricao' => '1922 - Lançamento efetuado a título de simples fa...nto decorrente de compra para recebimento futuro'],
                    109 => ['id' => '1923', 'descricao' => '1923 - Entrada de mercadoria recebida do vendedor remetente, em venda à ordem'],
                    110 => ['id' => '1924', 'descricao' => '1924 - Entrada para industrialização por conta e ...não transitar pelo estabelecimento do adquirente'],
                    111 => ['id' => '1925', 'descricao' => '1925 - Retorno de mercadoria remetida para indust...não transitar pelo estabelecimento do adquirente'],
                    112 => ['id' => '1926', 'descricao' => '1926 - Lançamento efetuado a título de reclassifi...ente de formação de "kit" ou de sua desagregação'],
                    113 => ['id' => '1931', 'descricao' => '1931 - Lançamento efetuado pelo tomador do serviç... transportador autônomo ou por transportador não'],
                    114 => ['id' => '1932', 'descricao' => '1932 - Aquisição de serviço de transporte iniciad... onde inscrito o prestador (Ajuste SINIEF 03/04)'],
                    115 => ['id' => '1933', 'descricao' => '1933 - Aquisição de serviço tributado pelo ISSQN (Ajuste SINIEF 03/04)'],
                    116 => ['id' => '1949', 'descricao' => '1949 - Outra entrada de mercadoria ou prestação de serviço não especificada'],
                    117 => ['id' => '2101', 'descricao' => '2101 - Compra para industrialização'],
                    118 => ['id' => '2102', 'descricao' => '2102 - Compra para comercialização'],
                    119 => ['id' => '2111', 'descricao' => '2111 - Compra para industrialização de mercadoria recebida anteriormente em consignação industrial'],
                    120 => ['id' => '2113', 'descricao' => '2113 - Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil'],
                    121 => ['id' => '2116', 'descricao' => '2116 - Compra para industrialização originada de encomenda para recebimento futuro'],
                    122 => ['id' => '2117', 'descricao' => '2117 - Compra para comercialização originada de encomenda para recebimento futuro'],
                    123 => ['id' => '2118', 'descricao' => '2118 - Compra de mercadoria para comercialização ...edor remetente ao destinatário, em venda à ordem'],
                    124 => ['id' => '2120', 'descricao' => '2120 - Compra para industrialização, em venda à ordem, já recebida do vendedor remetente'],
                    125 => ['id' => '2121', 'descricao' => '2121 - Compra para comercialização, em venda à ordem, já recebida do vendedor remetente'],
                    126 => ['id' => '2122', 'descricao' => '2122 - Compra para industrialização em que a merc...or sem transitar pelo estabelecimento adquirente'],
                    127 => ['id' => '2124', 'descricao' => '2124 - Industrialização efetuada por outra empresa'],
                    128 => ['id' => '2125', 'descricao' => '2125 - Industrialização efetuada por outra empres...ou pelo estabelecimento adquirente da mercadoria'],
                    129 => ['id' => '2126', 'descricao' => '2126 - Compra para utilização na prestação de serviço'],
                    130 => ['id' => '2151', 'descricao' => '2151 - Transferência para industrialização'],
                    131 => ['id' => '2152', 'descricao' => '2152 - Transferência para comercialização'],
                    132 => ['id' => '2153', 'descricao' => '2153 - Transferência de energia elétrica para distribuição'],
                    133 => ['id' => '2154', 'descricao' => '2154 - Transferência para utilização na prestação de serviço'],
                    134 => ['id' => '2201', 'descricao' => '2201 - Devolução de venda de produção do estabelecimento'],
                    135 => ['id' => '2202', 'descricao' => '2202 - Devolução de venda de mercadoria adquirida ou recebida de terceiros'],
                    136 => ['id' => '2203', 'descricao' => '2203 - Devolução de venda de produção do estabele...Zona Franca de Manaus ou Áreas de Livre Comércio'],
                    137 => ['id' => '2204', 'descricao' => '2204 - Devolução de venda de mercadoria adquirida...Zona Franca de Manaus ou Áreas de Livre Comércio'],
                    138 => ['id' => '2205', 'descricao' => '2205 - Anulação de valor relativo à prestação de serviço de comunicação'],
                    139 => ['id' => '2206', 'descricao' => '2206 - Anulação de valor relativo à prestação de serviço de transporte'],
                    140 => ['id' => '2207', 'descricao' => '2207 - Anulação de valor relativo à venda de energia elétrica'],
                    141 => ['id' => '2208', 'descricao' => '2208 - Devolução de produção do estabelecimento, remetida em transferência'],
                    142 => ['id' => '2209', 'descricao' => '2209 - Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência'],
                    143 => ['id' => '2251', 'descricao' => '2251 - Compra de energia elétrica para distribuição ou comercialização'],
                    144 => ['id' => '2252', 'descricao' => '2252 - Compra de energia elétrica por estabelecimento industrial'],
                    145 => ['id' => '2253', 'descricao' => '2253 - Compra de energia elétrica por estabelecimento comercial'],
                    146 => ['id' => '2254', 'descricao' => '2254 - Compra de energia elétrica por estabelecimento prestador de serviço de transporte'],
                    147 => ['id' => '2255', 'descricao' => '2255 - Compra de energia elétrica por estabelecimento prestador de serviço de comunicação'],
                    148 => ['id' => '2256', 'descricao' => '2256 - Compra de energia elétrica por estabelecimento de produtor rural'],
                    149 => ['id' => '2257', 'descricao' => '2257 - Compra de energia elétrica para consumo por demanda contratada'],
                    150 => ['id' => '2301', 'descricao' => '2301 - Aquisição de serviço de comunicação para execução de serviço da mesma natureza'],
                    151 => ['id' => '2302', 'descricao' => '2302 - Aquisição de serviço de comunicação por estabelecimento industrial'],
                    152 => ['id' => '2303', 'descricao' => '2303 - Aquisição de serviço de comunicação por estabelecimento comercial'],
                    153 => ['id' => '2304', 'descricao' => '2304 - Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte'],
                    154 => ['id' => '2305', 'descricao' => '2305 - Aquisição de serviço de comunicação por es...geradora ou de distribuidora de energia elétrica'],
                    155 => ['id' => '2306', 'descricao' => '2306 - Aquisição de serviço de comunicação por estabelecimento de produtor rural'],
                    156 => ['id' => '2351', 'descricao' => '2351 - Aquisição de serviço de transporte para execução de serviço da mesma natureza'],
                    157 => ['id' => '2352', 'descricao' => '2352 - Aquisição de serviço de transporte por estabelecimento industrial'],
                    158 => ['id' => '2353', 'descricao' => '2353 - Aquisição de serviço de transporte por estabelecimento comercial'],
                    159 => ['id' => '2354', 'descricao' => '2354 - Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação'],
                    160 => ['id' => '2355', 'descricao' => '2355 - Aquisição de serviço de transporte por est...geradora ou de distribuidora de energia elétrica'],
                    161 => ['id' => '2356', 'descricao' => '2356 - Aquisição de serviço de transporte por estabelecimento de produtor rural'],
                    162 => ['id' => '2401', 'descricao' => '2401 - Compra para industrialização em operação c...ria sujeita ao regime de substituição tributária'],
                    163 => ['id' => '2403', 'descricao' => '2403 - Compra para comercialização em operação co...ria sujeita ao regime de substituição tributária'],
                    164 => ['id' => '2406', 'descricao' => '2406 - Compra de bem para o ativo imobilizado cuj...stá sujeita ao regime de substituição tributária'],
                    165 => ['id' => '2407', 'descricao' => '2407 - Compra de mercadoria para uso ou consumo c...stá sujeita ao regime de substituição tributária'],
                    166 => ['id' => '2408', 'descricao' => '2408 - Transferência para industrialização em ope...ria sujeita ao regime de substituição tributária'],
                    167 => ['id' => '2409', 'descricao' => '2409 - Transferência para comercialização em oper...ria sujeita ao regime de substituição tributária'],
                    168 => ['id' => '2410', 'descricao' => '2410 - Devolução de venda de produção do estabele...uto sujeito ao regime de substituição tributária'],
                    169 => ['id' => '2411', 'descricao' => '2411 - Devolução de venda de mercadoria adquirida...ria sujeita ao regime de substituição tributária'],
                    170 => ['id' => '2414', 'descricao' => '2414 - Retorno de produção do estabelecimento, re...uto sujeito ao regime de substituição tributária'],
                    171 => ['id' => '2415', 'descricao' => '2415 - Retorno de mercadoria adquirida ou recebid...ria sujeita ao regime de substituição tributária'],
                    172 => ['id' => '2501', 'descricao' => '2501 - Entrada de mercadoria recebida com fim específico de exportação'],
                    173 => ['id' => '2503', 'descricao' => '2503 - Entrada decorrente de devolução de produto...co de exportação, de produção do estabelecimento'],
                    174 => ['id' => '2504', 'descricao' => '2504 - Entrada decorrente de devolução de mercado...e exportação, adquirida ou recebida de terceiros'],
                    175 => ['id' => '2551', 'descricao' => '2551 - Compra de bem para o ativo imobilizado'],
                    176 => ['id' => '2552', 'descricao' => '2552 - Transferência de bem do ativo imobilizado'],
                    177 => ['id' => '2553', 'descricao' => '2553 - Devolução de venda de bem do ativo imobilizado'],
                    178 => ['id' => '2554', 'descricao' => '2554 - Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento'],
                    179 => ['id' => '2555', 'descricao' => '2555 - Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento'],
                    180 => ['id' => '2556', 'descricao' => '2556 - Compra de material para uso ou consumo'],
                    181 => ['id' => '2557', 'descricao' => '2557 - Transferência de material para uso ou consumo'],
                    182 => ['id' => '2603', 'descricao' => '2603 - Ressarcimento de ICMS retido por substituição tributária'],
                    183 => ['id' => '2651', 'descricao' => '2651 - Compra de combustível ou lubrificante para industrialização subseqüente'],
                    184 => ['id' => '2652', 'descricao' => '2652 - Compra de combustível ou lubrificante para comercialização'],
                    185 => ['id' => '2653', 'descricao' => '2653 - Compra de combustível ou lubrificante por consumidor ou usuário final'],
                    186 => ['id' => '2658', 'descricao' => '2658 - Transferência de combustível e lubrificante para industrialização'],
                    187 => ['id' => '2659', 'descricao' => '2659 - Transferência de combustível e lubrificante para comercialização'],
                    188 => ['id' => '2660', 'descricao' => '2660 - Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente'],
                    189 => ['id' => '2661', 'descricao' => '2661 - Devolução de venda de combustível ou lubrificante destinado à comercialização'],
                    190 => ['id' => '2662', 'descricao' => '2662 - Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final'],
                    191 => ['id' => '2663', 'descricao' => '2663 - Entrada de combustível ou lubrificante para armazenagem'],
                    192 => ['id' => '2664', 'descricao' => '2664 - Retorno de combustível ou lubrificante remetido para armazenagem'],
                    193 => ['id' => '2901', 'descricao' => '2901 - Entrada para industrialização por encomenda'],
                    194 => ['id' => '2902', 'descricao' => '2902 - Retorno de mercadoria remetida para industrialização por encomenda'],
                    195 => ['id' => '2903', 'descricao' => '2903 - Entrada de mercadoria remetida para industrialização e não aplicada no referido processo'],
                    196 => ['id' => '2904', 'descricao' => '2904 - Retorno de remessa para venda fora do estabelecimento'],
                    197 => ['id' => '2905', 'descricao' => '2905 - Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral'],
                    198 => ['id' => '2906', 'descricao' => '2906 - Retorno de mercadoria remetida para depósito fechado ou armazém geral'],
                    199 => ['id' => '2907', 'descricao' => '2907 - Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral'],
                    200 => ['id' => '2908', 'descricao' => '2908 - Entrada de bem por conta de contrato de comodato'],
                    201 => ['id' => '2909', 'descricao' => '2909 - Retorno de bem remetido por conta de contrato de comodato'],
                    202 => ['id' => '2910', 'descricao' => '2910 - Entrada de bonificação, doação ou brinde'],
                    203 => ['id' => '2911', 'descricao' => '2911 - Entrada de amostra grátis'],
                    204 => ['id' => '2912', 'descricao' => '2912 - Entrada de mercadoria ou bem recebido para demonstração'],
                    205 => ['id' => '2913', 'descricao' => '2913 - Retorno de mercadoria ou bem remetido para demonstração'],
                    206 => ['id' => '2914', 'descricao' => '2914 - Retorno de mercadoria ou bem remetido para exposição ou feira'],
                    207 => ['id' => '2915', 'descricao' => '2915 - Entrada de mercadoria ou bem recebido para conserto ou reparo'],
                    208 => ['id' => '2916', 'descricao' => '2916 - Retorno de mercadoria ou bem remetido para conserto ou reparo'],
                    209 => ['id' => '2917', 'descricao' => '2917 - Entrada de mercadoria recebida em consignação mercantil ou industrial'],
                    210 => ['id' => '2918', 'descricao' => '2918 - Devolução de mercadoria remetida em consignação mercantil ou industrial'],
                    211 => ['id' => '2919', 'descricao' => '2919 - Devolução simbólica de mercadoria vendida ...riormente em consignação mercantil ou industrial'],
                    212 => ['id' => '2920', 'descricao' => '2920 - Entrada de vasilhame ou sacaria'],
                    213 => ['id' => '2921', 'descricao' => '2921 - Retorno de vasilhame ou sacaria'],
                    214 => ['id' => '2922', 'descricao' => '2922 - Lançamento efetuado a título de simples fa...nto decorrente de compra para recebimento futuro'],
                    215 => ['id' => '2923', 'descricao' => '2923 - Entrada de mercadoria recebida do vendedor remetente, em venda à ordem'],
                    216 => ['id' => '2924', 'descricao' => '2924 - Entrada para industrialização por conta e ...não transitar pelo estabelecimento do adquirente'],
                    217 => ['id' => '2925', 'descricao' => '2925 - Retorno de mercadoria remetida para indust...não transitar pelo estabelecimento do adquirente'],
                    218 => ['id' => '2931', 'descricao' => '2931 - Lançamento efetuado pelo tomador do serviç... transportador autônomo ou por transportador não'],
                    219 => ['id' => '2932', 'descricao' => '2932 - Aquisição de serviço de transporte iniciad... onde inscrito o prestador (Ajuste SINIEF 03/04)'],
                    220 => ['id' => '2933', 'descricao' => '2933 - Aquisição de serviço tributado pelo ISSQN (Ajuste SINIEF 03/04)'],
                    221 => ['id' => '2949', 'descricao' => '2949 - Outra entrada de mercadoria ou prestação de serviço não especificado'],
                    222 => ['id' => '3101', 'descricao' => '3101 - Compra para industrialização'],
                    223 => ['id' => '3102', 'descricao' => '3102 - Compra para comercialização'],
                    224 => ['id' => '3126', 'descricao' => '3126 - Compra para utilização na prestação de serviço'],
                    225 => ['id' => '3127', 'descricao' => '3127 - Compra para industrialização sob o regime de "drawback"'],
                    226 => ['id' => '3200', 'descricao' => '3200 - DEVOLUÇÕES DE VENDAS DE PRODUÇÃO PRÓPRIA, DE TERCEIROS OU ANULAÇÕES DE VALORES'],
                    227 => ['id' => '3201', 'descricao' => '3201 - Devolução de venda de produção do estabelecimento'],
                    228 => ['id' => '3202', 'descricao' => '3202 - Devolução de venda de mercadoria adquirida ou recebida de terceiros'],
                    229 => ['id' => '3205', 'descricao' => '3205 - Anulação de valor relativo à prestação de serviço de comunicação'],
                    230 => ['id' => '3206', 'descricao' => '3206 - Anulação de valor relativo à prestação de serviço de transporte'],
                    231 => ['id' => '3207', 'descricao' => '3207 - Anulação de valor relativo à venda de energia elétrica'],
                    232 => ['id' => '3211', 'descricao' => '3211 - Devolução de venda de produção do estabelecimento sob o regime de "drawback"'],
                    233 => ['id' => '3251', 'descricao' => '3251 - Compra de energia elétrica para distribuição ou comercialização'],
                    234 => ['id' => '3301', 'descricao' => '3301 - Aquisição de serviço de comunicação para execução de serviço da mesma natureza'],
                    235 => ['id' => '3351', 'descricao' => '3351 - Aquisição de serviço de transporte para execução de serviço da mesma natureza'],
                    236 => ['id' => '3352', 'descricao' => '3352 - Aquisição de serviço de transporte por estabelecimento industrial'],
                    237 => ['id' => '3353', 'descricao' => '3353 - Aquisição de serviço de transporte por estabelecimento comercial'],
                    238 => ['id' => '3354', 'descricao' => '3354 - Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação'],
                    239 => ['id' => '3355', 'descricao' => '3355 - Aquisição de serviço de transporte por est...geradora ou de distribuidora de energia elétrica'],
                    240 => ['id' => '3356', 'descricao' => '3356 - Aquisição de serviço de transporte por estabelecimento de produtor rural'],
                    241 => ['id' => '3503', 'descricao' => '3503 - Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação'],
                    242 => ['id' => '3551', 'descricao' => '3551 - Compra de bem para o ativo imobilizado'],
                    243 => ['id' => '3553', 'descricao' => '3553 - Devolução de venda de bem do ativo imobilizado'],
                    244 => ['id' => '3556', 'descricao' => '3556 - Compra de material para uso ou consumo'],
                    245 => ['id' => '3651', 'descricao' => '3651 - Compra de combustível ou lubrificante para industrialização subseqüente'],
                    246 => ['id' => '3652', 'descricao' => '3652 - Compra de combustível ou lubrificante para comercialização'],
                    247 => ['id' => '3653', 'descricao' => '3653 - Compra de combustível ou lubrificante por consumidor ou usuário final'],
                    248 => ['id' => '3900', 'descricao' => '3900 - OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS'],
                    249 => ['id' => '3930', 'descricao' => '3930 - Lançamento efetuado a título de entrada de...regime especial aduaneiro de admissão temporária'],
                    250 => ['id' => '3949', 'descricao' => '3949 - Outra entrada de mercadoria ou prestação de serviço não especificado'],
                    251 => ['id' => '5102', 'descricao' => '5102 - Venda de mercadoria adquirida ou recebida de terceiros'],
                    252 => ['id' => '5103', 'descricao' => '5103 - Venda de produção do estabelecimento, efetuada fora do estabelecimento'],
                    253 => ['id' => '5104', 'descricao' => '5104 - Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento'],
                    254 => ['id' => '5105', 'descricao' => '5105 - Venda de produção do estabelecimento que não deva por ele transitar'],
                    255 => ['id' => '5106', 'descricao' => '5106 - Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar'],
                    256 => ['id' => '5109', 'descricao' => '5109 - Venda de produção do estabelecimento, dest...Zona Franca de Manaus ou Áreas de Livre Comércio'],
                    257 => ['id' => '5110', 'descricao' => '5110 - Venda de mercadoria adquirida ou recebida ...Zona Franca de Manaus ou Áreas de Livre Comércio'],
                    258 => ['id' => '5111', 'descricao' => '5111 - Venda de produção do estabelecimento remetida anteriormente em consignação industrial'],
                    259 => ['id' => '5112', 'descricao' => '5112 - Venda de mercadoria adquirida ou recebida ...remetida anteriormente em consignação industrial'],
                    260 => ['id' => '5113', 'descricao' => '5113 - Venda de produção do estabelecimento remetida anteriormente em consignação mercantil'],
                    261 => ['id' => '5114', 'descricao' => '5114 - Venda de mercadoria adquirida ou recebida ... remetida anteriormente em consignação mercantil'],
                    262 => ['id' => '5115', 'descricao' => '5115 - Venda de mercadoria adquirida ou recebida ... recebida anteriormente em consignação mercantil'],
                    263 => ['id' => '5116', 'descricao' => '5116 - Venda de produção do estabelecimento originada de encomenda para entrega futura'],
                    264 => ['id' => '5117', 'descricao' => '5117 - Venda de mercadoria adquirida ou recebida ...iros, originada de encomenda para entrega futura'],
                    265 => ['id' => '5118', 'descricao' => '5118 - Venda de produção do estabelecimento entre...ordem do adquirente originário, em venda à ordem'],
                    266 => ['id' => '5119', 'descricao' => '5119 - Venda de mercadoria adquirida ou recebida ...ordem do adquirente originário, em venda à ordem'],
                    267 => ['id' => '5120', 'descricao' => '5120 - Venda de mercadoria adquirida ou recebida ...atário pelo vendedor remetente, em venda à ordem'],
                    268 => ['id' => '5122', 'descricao' => '5122 - Venda de produção do estabelecimento remet...sem transitar pelo estabelecimento do adquirente'],
                    269 => ['id' => '5123', 'descricao' => '5123 - Venda de mercadoria adquirida ou recebida ...sem transitar pelo estabelecimento do adquirente'],
                    270 => ['id' => '5124', 'descricao' => '5124 - Industrialização efetuada para outra empresa'],
                    271 => ['id' => '5125', 'descricao' => '5125 - Industrialização efetuada para outra empre...ar pelo estabelecimento adquirente da mercadoria'],
                    272 => ['id' => '5151', 'descricao' => '5151 - Transferência de produção do estabelecimento'],
                    273 => ['id' => '5152', 'descricao' => '5152 - Transferência de mercadoria adquirida ou recebida de terceiros'],
                    274 => ['id' => '5153', 'descricao' => '5153 - Transferência de energia elétrica'],
                    275 => ['id' => '5155', 'descricao' => '5155 - Transferência de produção do estabelecimento, que não deva por ele transitar'],
                    276 => ['id' => '5156', 'descricao' => '5156 - Transferência de mercadoria adquirida ou r...ida de terceiros, que não deva por ele transitar'],
                    277 => ['id' => '5201', 'descricao' => '5201 - Devolução de compra para industrialização'],
                    278 => ['id' => '5202', 'descricao' => '5202 - Devolução de compra para comercialização'],
                    279 => ['id' => '5205', 'descricao' => '5205 - Anulação de valor relativo a aquisição de serviço de comunicação'],
                    280 => ['id' => '5206', 'descricao' => '5206 - Anulação de valor relativo a aquisição de serviço de transporte'],
                    281 => ['id' => '5207', 'descricao' => '5207 - Anulação de valor relativo à compra de energia elétrica'],
                    282 => ['id' => '5208', 'descricao' => '5208 - Devolução de mercadoria recebida em transferência para industrialização'],
                    283 => ['id' => '5209', 'descricao' => '5209 - Devolução de mercadoria recebida em transferência para comercialização'],
                    284 => ['id' => '5210', 'descricao' => '5210 - Devolução de compra para utilização na prestação de serviço'],
                    285 => ['id' => '5251', 'descricao' => '5251 - Venda de energia elétrica para distribuição ou comercialização'],
                    286 => ['id' => '5252', 'descricao' => '5252 - Venda de energia elétrica para estabelecimento industrial'],
                    287 => ['id' => '5253', 'descricao' => '5253 - Venda de energia elétrica para estabelecimento comercial'],
                    288 => ['id' => '5254', 'descricao' => '5254 - Venda de energia elétrica para estabelecimento prestador de serviço de transporte'],
                    289 => ['id' => '5255', 'descricao' => '5255 - Venda de energia elétrica para estabelecimento prestador de serviço de comunicação'],
                    290 => ['id' => '5256', 'descricao' => '5256 - Venda de energia elétrica para estabelecimento de produtor rural'],
                    291 => ['id' => '5257', 'descricao' => '5257 - Venda de energia elétrica para consumo por demanda contratada'],
                    292 => ['id' => '5258', 'descricao' => '5258 - Venda de energia elétrica a não contribuinte'],
                    293 => ['id' => '5301', 'descricao' => '5301 - Prestação de serviço de comunicação para execução de serviço da mesma natureza'],
                    294 => ['id' => '5302', 'descricao' => '5302 - Prestação de serviço de comunicação a estabelecimento industrial'],
                    295 => ['id' => '5303', 'descricao' => '5303 - Prestação de serviço de comunicação a estabelecimento comercial'],
                    296 => ['id' => '5304', 'descricao' => '5304 - Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte'],
                    297 => ['id' => '5305', 'descricao' => '5305 - Prestação de serviço de comunicação a esta...geradora ou de distribuidora de energia elétrica'],
                    298 => ['id' => '5306', 'descricao' => '5306 - Prestação de serviço de comunicação a estabelecimento de produtor rural'],
                    299 => ['id' => '5307', 'descricao' => '5307 - Prestação de serviço de comunicação a não contribuinte'],
                    300 => ['id' => '5351', 'descricao' => '5351 - Prestação de serviço de transporte para execução de serviço da mesma natureza'],
                    301 => ['id' => '5352', 'descricao' => '5352 - Prestação de serviço de transporte a estabelecimento industrial'],
                    302 => ['id' => '5353', 'descricao' => '5353 - Prestação de serviço de transporte a estabelecimento comercial'],
                    303 => ['id' => '5354', 'descricao' => '5354 - Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação'],
                    304 => ['id' => '5355', 'descricao' => '5355 - Prestação de serviço de transporte a estab...geradora ou de distribuidora de energia elétrica'],
                    305 => ['id' => '5356', 'descricao' => '5356 - Prestação de serviço de transporte a estabelecimento de produtor rural'],
                    306 => ['id' => '5357', 'descricao' => '5357 - Prestação de serviço de transporte a não contribuinte'],
                    307 => ['id' => '5359', 'descricao' => '5359 - Prestação de serviço de transporte a contr... de emissão de nota fiscal (Ajuste SINIEF 03/04)'],
                    308 => ['id' => '5401', 'descricao' => '5401 - Venda de produção do estabelecimento em op...ibutária, na condição de contribuinte substituto'],
                    309 => ['id' => '5402', 'descricao' => '5402 - Venda de produção do estabelecimento de pr...entre contribuintes substitutos do mesmo produto'],
                    310 => ['id' => '5403', 'descricao' => '5403 - Venda de mercadoria adquirida ou recebida ...ibutária, na condição de contribuinte substituto'],
                    311 => ['id' => '5405', 'descricao' => '5405 - Venda de mercadoria adquirida ou recebida ...butária, na condição de contribuinte substituído'],
                    312 => ['id' => '5408', 'descricao' => '5408 - Transferência de produção do estabelecimen...uto sujeito ao regime de substituição tributária'],
                    313 => ['id' => '5409', 'descricao' => '5409 - Transferência de mercadoria adquirida ou r...ria sujeita ao regime de substituição tributária'],
                    314 => ['id' => '5410', 'descricao' => '5410 - Devolução de compra para industrialização ...ria sujeita ao regime de substituição tributária'],
                    315 => ['id' => '5411', 'descricao' => '5411 - Devolução de compra para comercialização e...ria sujeita ao regime de substituição tributária'],
                    316 => ['id' => '5412', 'descricao' => '5412 - Devolução de bem do ativo imobilizado, em ...ria sujeita ao regime de substituição tributária'],
                    317 => ['id' => '5413', 'descricao' => '5413 - Devolução de mercadoria destinada ao uso o...ria sujeita ao regime de substituição tributária'],
                    318 => ['id' => '5414', 'descricao' => '5414 - Remessa de produção do estabelecimento par...uto sujeito ao regime de substituição tributária'],
                    319 => ['id' => '5415', 'descricao' => '5415 - Remessa de mercadoria adquirida ou recebid...ria sujeita ao regime de substituição tributária'],
                    320 => ['id' => '5451', 'descricao' => '5451 - Remessa de animal e de insumo para estabelecimento produtor'],
                    321 => ['id' => '5500', 'descricao' => '5500 - REMESSAS COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES'],
                    322 => ['id' => '5501', 'descricao' => '5501 - Remessa de produção do estabelecimento, com fim específico de exportação'],
                    323 => ['id' => '5502', 'descricao' => '5502 - Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação'],
                    324 => ['id' => '5503', 'descricao' => '5503 - Devolução de mercadoria recebida com fim específico de exportação'],
                    325 => ['id' => '5551', 'descricao' => '5551 - Venda de bem do ativo imobilizado'],
                    326 => ['id' => '5552', 'descricao' => '5552 - Transferência de bem do ativo imobilizado'],
                    327 => ['id' => '5553', 'descricao' => '5553 - Devolução de compra de bem para o ativo imobilizado'],
                    328 => ['id' => '5554', 'descricao' => '5554 - Remessa de bem do ativo imobilizado para uso fora do estabelecimento'],
                    329 => ['id' => '5555', 'descricao' => '5555 - Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento'],
                    330 => ['id' => '5556', 'descricao' => '5556 - Devolução de compra de material de uso ou consumo'],
                    331 => ['id' => '5557', 'descricao' => '5557 - Transferência de material de uso ou consumo'],
                    332 => ['id' => '5601', 'descricao' => '5601 - Transferência de crédito de ICMS acumulado'],
                    333 => ['id' => '5602', 'descricao' => '5602 - Transferência de saldo credor de ICMS para...destinado à compensação de saldo devedor de ICMS'],
                    334 => ['id' => '5603', 'descricao' => '5603 - Ressarcimento de ICMS retido por substituição tributária'],
                    335 => ['id' => '5605', 'descricao' => '5605 - Transferência de saldo devedor de ICMS de ...lecimento da mesma empresa (Ajuste SINIEF 03/04)'],
                    336 => ['id' => '5651', 'descricao' => '5651 - Venda de combustível ou lubrificante de pr...cimento destinado à industrialização subseqüente'],
                    337 => ['id' => '5652', 'descricao' => '5652 - Venda de combustível ou lubrificante de pr...o do estabelecimento destinado à comercialização'],
                    338 => ['id' => '5653', 'descricao' => '5653 - Venda de combustível ou lubrificante de pr...ecimento destinado a consumidor ou usuário final'],
                    339 => ['id' => '5654', 'descricao' => '5654 - Venda de combustível ou lubrificante adqui...rceiros destinado à industrialização subseqüente'],
                    340 => ['id' => '5655', 'descricao' => '5655 - Venda de combustível ou lubrificante adqui...ecebido de terceiros destinado à comercialização'],
                    341 => ['id' => '5656', 'descricao' => '5656 - Venda de combustível ou lubrificante adqui...erceiros destinado a consumidor ou usuário final'],
                    342 => ['id' => '5657', 'descricao' => '5657 - Remessa de combustível ou lubrificante adq... de terceiros para venda fora do estabelecimento'],
                    343 => ['id' => '5658', 'descricao' => '5658 - Transferência de combustível ou lubrificante de produção do estabelecimento'],
                    344 => ['id' => '5659', 'descricao' => '5659 - Transferência de combustível ou lubrificante adquirido ou recebido de terceiro'],
                    345 => ['id' => '5661', 'descricao' => '5661 - Devolução de compra de combustível ou lubrificante adquirido para comercialização'],
                    346 => ['id' => '5662', 'descricao' => '5662 - Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final'],
                    347 => ['id' => '5663', 'descricao' => '5663 - Remessa para armazenagem de combustível ou lubrificante'],
                    348 => ['id' => '5664', 'descricao' => '5664 - Retorno de combustível ou lubrificante recebido para armazenagem'],
                    349 => ['id' => '5665', 'descricao' => '5665 - Retorno simbólico de combustível ou lubrificante recebido para armazenagem'],
                    350 => ['id' => '5666', 'descricao' => '5666 - Remessa por conta e ordem de terceiros de ...stível ou lubrificante recebido para armazenagem'],
                    351 => ['id' => '5901', 'descricao' => '5901 - Remessa para industrialização por encomenda'],
                    352 => ['id' => '5902', 'descricao' => '5902 - Retorno de mercadoria utilizada na industrialização por encomenda'],
                    353 => ['id' => '5903', 'descricao' => '5903 - Retorno de mercadoria recebida para industrialização e não aplicada no referido processo'],
                    354 => ['id' => '5904', 'descricao' => '5904 - Remessa para venda fora do estabelecimento'],
                    355 => ['id' => '5905', 'descricao' => '5905 - Remessa para depósito fechado ou armazém geral'],
                    356 => ['id' => '5906', 'descricao' => '5906 - Retorno de mercadoria depositada em depósito fechado ou armazém geral'],
                    357 => ['id' => '5907', 'descricao' => '5907 - Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral'],
                    358 => ['id' => '5908', 'descricao' => '5908 - Remessa de bem por conta de contrato de comodato'],
                    359 => ['id' => '5909', 'descricao' => '5909 - Retorno de bem recebido por conta de contrato de comodato'],
                    360 => ['id' => '5910', 'descricao' => '5910 - Remessa em bonificação, doação ou brinde'],
                    361 => ['id' => '5911', 'descricao' => '5911 - Remessa de amostra grátis'],
                    362 => ['id' => '5912', 'descricao' => '5912 - Remessa de mercadoria ou bem para demonstração'],
                    363 => ['id' => '5913', 'descricao' => '5913 - Retorno de mercadoria ou bem recebido para demonstração'],
                    364 => ['id' => '5914', 'descricao' => '5914 - Remessa de mercadoria ou bem para exposição ou feira'],
                    365 => ['id' => '5915', 'descricao' => '5915 - Remessa de mercadoria ou bem para conserto ou reparo'],
                    366 => ['id' => '5916', 'descricao' => '5916 - Retorno de mercadoria ou bem recebido para conserto ou reparo'],
                    367 => ['id' => '5917', 'descricao' => '5917 - Remessa de mercadoria em consignação mercantil ou industrial'],
                    368 => ['id' => '5918', 'descricao' => '5918 - Devolução de mercadoria recebida em consignação mercantil ou industrial'],
                    369 => ['id' => '5919', 'descricao' => '5919 - Devolução simbólica de mercadoria vendida ...riormente em consignação mercantil ou industrial'],
                    370 => ['id' => '5920', 'descricao' => '5920 - Remessa de vasilhame ou sacaria'],
                    371 => ['id' => '5921', 'descricao' => '5921 - Devolução de vasilhame ou sacaria'],
                    372 => ['id' => '5922', 'descricao' => '5922 - Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura'],
                    373 => ['id' => '5923', 'descricao' => '5923 - Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem'],
                    374 => ['id' => '5924', 'descricao' => '5924 - Remessa para industrialização por conta e ...não transitar pelo estabelecimento do adquirente'],
                    375 => ['id' => '5925', 'descricao' => '5925 - Retorno de mercadoria recebida para indust...não transitar pelo estabelecimento do adquirente'],
                    376 => ['id' => '5926', 'descricao' => '5926 - Lançamento efetuado a título de reclassifi...ente de formação de "kit" ou de sua desagregação'],
                    377 => ['id' => '5927', 'descricao' => '5927 - Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração'],
                    378 => ['id' => '5928', 'descricao' => '5928 - Lançamento efetuado a título de baixa de e...corrente do encerramento da atividade da empresa'],
                    379 => ['id' => '5929', 'descricao' => '5929 - Lançamento efetuado em decorrência de emis...ada em equipamento Emissor de Cupom Fiscal - ECF'],
                    380 => ['id' => '5931', 'descricao' => '5931 - Lançamento efetuado em decorrência da resp...nsportador autônomo ou por transportador não ins'],
                    381 => ['id' => '5932', 'descricao' => '5932 - Prestação de serviço de transporte iniciad...eração diversa daquela onde inscrito o prestador'],
                    382 => ['id' => '5933', 'descricao' => '5933 - Prestação de serviço tributado pelo ISSQN (Ajuste SINIEF 03/04)'],
                    383 => ['id' => '6102', 'descricao' => '6102 - Venda de mercadoria adquirida ou recebida de terceiros'],
                    384 => ['id' => '6103', 'descricao' => '6103 - Venda de produção do estabelecimento, efetuada fora do estabelecimento'],
                    385 => ['id' => '6104', 'descricao' => '6104 - Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento'],
                    386 => ['id' => '6105', 'descricao' => '6105 - Venda de produção do estabelecimento que não deva por ele transitar'],
                    387 => ['id' => '6106', 'descricao' => '6106 - Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar'],
                    388 => ['id' => '6107', 'descricao' => '6107 - Venda de produção do estabelecimento, destinada a não contribuinte'],
                    389 => ['id' => '6108', 'descricao' => '6108 - Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte'],
                    390 => ['id' => '6109', 'descricao' => '6109 - Venda de produção do estabelecimento, dest...Zona Franca de Manaus ou Áreas de Livre Comércio'],
                    391 => ['id' => '6110', 'descricao' => '6110 - Venda de mercadoria adquirida ou recebida ...Zona Franca de Manaus ou Áreas de Livre Comércio'],
                    392 => ['id' => '6111', 'descricao' => '6111 - Venda de produção do estabelecimento remetida anteriormente em consignação industrial'],
                    393 => ['id' => '6112', 'descricao' => '6112 - Venda de mercadoria adquirida ou recebida ...remetida anteriormente em consignação industrial'],
                    394 => ['id' => '6113', 'descricao' => '6113 - Venda de produção do estabelecimento remetida anteriormente em consignação mercantil'],
                    395 => ['id' => '6114', 'descricao' => '6114 - Venda de mercadoria adquirida ou recebida ... remetida anteriormente em consignação mercantil'],
                    396 => ['id' => '6115', 'descricao' => '6115 - Venda de mercadoria adquirida ou recebida ... recebida anteriormente em consignação mercantil'],
                    397 => ['id' => '6116', 'descricao' => '6116 - Venda de produção do estabelecimento originada de encomenda para entrega futura'],
                    398 => ['id' => '6117', 'descricao' => '6117 - Venda de mercadoria adquirida ou recebida ...iros, originada de encomenda para entrega futura'],
                    399 => ['id' => '6118', 'descricao' => '6118 - Venda de produção do estabelecimento entre...ordem do adquirente originário, em venda à ordem'],
                    400 => ['id' => '6119', 'descricao' => '6119 - Venda de mercadoria adquirida ou recebida ...ordem do adquirente originário, em venda à ordem'],
                    401 => ['id' => '6120', 'descricao' => '6120 - Venda de mercadoria adquirida ou recebida ...atário pelo vendedor remetente, em venda à ordem'],
                    402 => ['id' => '6122', 'descricao' => '6122 - Venda de produção do estabelecimento remet...sem transitar pelo estabelecimento do adquirente'],
                    403 => ['id' => '6123', 'descricao' => '6123 - Venda de mercadoria adquirida ou recebida ...sem transitar pelo estabelecimento do adquirente'],
                    404 => ['id' => '6124', 'descricao' => '6124 - Industrialização efetuada para outra empresa'],
                    405 => ['id' => '6125', 'descricao' => '6125 - Industrialização efetuada para outra empre...ar pelo estabelecimento adquirente da mercadoria'],
                    406 => ['id' => '6151', 'descricao' => '6151 - Transferência de produção do estabelecimento'],
                    407 => ['id' => '6152', 'descricao' => '6152 - Transferência de mercadoria adquirida ou recebida de terceiros'],
                    408 => ['id' => '6153', 'descricao' => '6153 - Transferência de energia elétrica'],
                    409 => ['id' => '6155', 'descricao' => '6155 - Transferência de produção do estabelecimento, que não deva por ele transitar'],
                    410 => ['id' => '6156', 'descricao' => '6156 - Transferência de mercadoria adquirida ou r...ida de terceiros, que não deva por ele transitar'],
                    411 => ['id' => '6201', 'descricao' => '6201 - Devolução de compra para industrialização'],
                    412 => ['id' => '6202', 'descricao' => '6202 - Devolução de compra para comercialização'],
                    413 => ['id' => '6205', 'descricao' => '6205 - Anulação de valor relativo a aquisição de serviço de comunicação'],
                    414 => ['id' => '6206', 'descricao' => '6206 - Anulação de valor relativo a aquisição de serviço de transporte'],
                    415 => ['id' => '6207', 'descricao' => '6207 - Anulação de valor relativo à compra de energia elétrica'],
                    416 => ['id' => '6208', 'descricao' => '6208 - Devolução de mercadoria recebida em transferência para industrialização'],
                    417 => ['id' => '6209', 'descricao' => '6209 - Devolução de mercadoria recebida em transferência para comercialização'],
                    418 => ['id' => '6210', 'descricao' => '6210 - Devolução de compra para utilização na prestação de serviço'],
                    419 => ['id' => '6251', 'descricao' => '6251 - Venda de energia elétrica para distribuição ou comercialização'],
                    420 => ['id' => '6252', 'descricao' => '6252 - Venda de energia elétrica para estabelecimento industrial'],
                    421 => ['id' => '6253', 'descricao' => '6253 - Venda de energia elétrica para estabelecimento comercial'],
                    422 => ['id' => '6254', 'descricao' => '6254 - Venda de energia elétrica para estabelecimento prestador de serviço de transporte'],
                    423 => ['id' => '6255', 'descricao' => '6255 - Venda de energia elétrica para estabelecimento prestador de serviço de comunicação'],
                    424 => ['id' => '6256', 'descricao' => '6256 - Venda de energia elétrica para estabelecimento de produtor rural'],
                    425 => ['id' => '6257', 'descricao' => '6257 - Venda de energia elétrica para consumo por demanda contratada'],
                    426 => ['id' => '6258', 'descricao' => '6258 - Venda de energia elétrica a não contribuinte'],
                    427 => ['id' => '6301', 'descricao' => '6301 - Prestação de serviço de comunicação para execução de serviço da mesma natureza'],
                    428 => ['id' => '6302', 'descricao' => '6302 - Prestação de serviço de comunicação a estabelecimento industrial'],
                    429 => ['id' => '6303', 'descricao' => '6303 - Prestação de serviço de comunicação a estabelecimento comercial'],
                    430 => ['id' => '6304', 'descricao' => '6304 - Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte'],
                    431 => ['id' => '6305', 'descricao' => '6305 - Prestação de serviço de comunicação a esta...geradora ou de distribuidora de energia elétrica'],
                    432 => ['id' => '6306', 'descricao' => '6306 - Prestação de serviço de comunicação a estabelecimento de produtor rural'],
                    433 => ['id' => '6307', 'descricao' => '6307 - Prestação de serviço de comunicação a não contribuinte'],
                    434 => ['id' => '6351', 'descricao' => '6351 - Prestação de serviço de transporte para execução de serviço da mesma natureza'],
                    435 => ['id' => '6352', 'descricao' => '6352 - Prestação de serviço de transporte a estabelecimento industrial'],
                    436 => ['id' => '6353', 'descricao' => '6353 - Prestação de serviço de transporte a estabelecimento comercial'],
                    437 => ['id' => '6354', 'descricao' => '6354 - Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação'],
                    438 => ['id' => '6355', 'descricao' => '6355 - Prestação de serviço de transporte a estab...geradora ou de distribuidora de energia elétrica'],
                    439 => ['id' => '6356', 'descricao' => '6356 - Prestação de serviço de transporte a estabelecimento de produtor rural'],
                    440 => ['id' => '6357', 'descricao' => '6357 - Prestação de serviço de transporte a não contribuinte'],
                    441 => ['id' => '6359', 'descricao' => '6359 - Prestação de serviço de transporte a contr... de emissão de nota fiscal (Ajuste SINIEF 03/04)'],
                    442 => ['id' => '6401', 'descricao' => '6401 - Venda de produção do estabelecimento em op...ibutária, na condição de contribuinte substituto'],
                    443 => ['id' => '6402', 'descricao' => '6402 - Venda de produção do estabelecimento de pr...entre contribuintes substitutos do mesmo produto'],
                    444 => ['id' => '6403', 'descricao' => '6403 - Venda de mercadoria adquirida ou recebida ...ibutária, na condição de contribuinte substituto'],
                    445 => ['id' => '6404', 'descricao' => '6404 - Venda de mercadoria sujeita ao regime de s... cujo imposto já tenha sido retido anteriormente'],
                    446 => ['id' => '6408', 'descricao' => '6408 - Transferência de produção do estabelecimen...uto sujeito ao regime de substituição tributária'],
                    447 => ['id' => '6409', 'descricao' => '6409 - Transferência de mercadoria adquirida ou r...ria sujeita ao regime de substituição tributária'],
                    448 => ['id' => '6410', 'descricao' => '6410 - Devolução de compra para industrialização ...ria sujeita ao regime de substituição tributária'],
                    449 => ['id' => '6411', 'descricao' => '6411 - Devolução de compra para comercialização e...ria sujeita ao regime de substituição tributária'],
                    450 => ['id' => '6412', 'descricao' => '6412 - Devolução de bem do ativo imobilizado, em ...ria sujeita ao regime de substituição tributária'],
                    451 => ['id' => '6413', 'descricao' => '6413 - Devolução de mercadoria destinada ao uso o...ria sujeita ao regime de substituição tributária'],
                    452 => ['id' => '6414', 'descricao' => '6414 - Remessa de produção do estabelecimento par...uto sujeito ao regime de substituição tributária'],
                    453 => ['id' => '6415', 'descricao' => '6415 - Remessa de mercadoria adquirida ou recebid...ria sujeita ao regime de substituição tributária'],
                    454 => ['id' => '6501', 'descricao' => '6501 - Remessa de produção do estabelecimento, com fim específico de exportação'],
                    455 => ['id' => '6502', 'descricao' => '6502 - Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação'],
                    456 => ['id' => '6503', 'descricao' => '6503 - Devolução de mercadoria recebida com fim específico de exportação'],
                    457 => ['id' => '6551', 'descricao' => '6551 - Venda de bem do ativo imobilizado'],
                    458 => ['id' => '6552', 'descricao' => '6552 - Transferência de bem do ativo imobilizado'],
                    459 => ['id' => '6553', 'descricao' => '6553 - Devolução de compra de bem para o ativo imobilizado'],
                    460 => ['id' => '6554', 'descricao' => '6554 - Remessa de bem do ativo imobilizado para uso fora do estabelecimento'],
                    461 => ['id' => '6555', 'descricao' => '6555 - Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento'],
                    462 => ['id' => '6556', 'descricao' => '6556 - Devolução de compra de material de uso ou consumo'],
                    463 => ['id' => '6557', 'descricao' => '6557 - Transferência de material de uso ou consumo'],
                    464 => ['id' => '6603', 'descricao' => '6603 - Ressarcimento de ICMS retido por substituição tributária'],
                    465 => ['id' => '6651', 'descricao' => '6651 - Venda de combustível ou lubrificante de pr...cimento destinado à industrialização subseqüente'],
                    466 => ['id' => '6652', 'descricao' => '6652 - Venda de combustível ou lubrificante de pr...o do estabelecimento destinado à comercialização'],
                    467 => ['id' => '6653', 'descricao' => '6653 - Venda de combustível ou lubrificante de pr...ecimento destinado a consumidor ou usuário final'],
                    468 => ['id' => '6654', 'descricao' => '6654 - Venda de combustível ou lubrificante adqui...rceiros destinado à industrialização subseqüente'],
                    469 => ['id' => '6655', 'descricao' => '6655 - Venda de combustível ou lubrificante adqui...ecebido de terceiros destinado à comercialização'],
                    470 => ['id' => '6656', 'descricao' => '6656 - Venda de combustível ou lubrificante adqui...erceiros destinado a consumidor ou usuário final'],
                    471 => ['id' => '6657', 'descricao' => '6657 - Remessa de combustível ou lubrificante adq... de terceiros para venda fora do estabelecimento'],
                    472 => ['id' => '6658', 'descricao' => '6658 - Transferência de combustível ou lubrificante de produção do estabelecimento'],
                    473 => ['id' => '6659', 'descricao' => '6659 - Transferência de combustível ou lubrificante adquirido ou recebido de terceiro'],
                    474 => ['id' => '6660', 'descricao' => '6660 - Devolução de compra de combustível ou lubr...ante adquirido para industrialização subseqüente'],
                    475 => ['id' => '6661', 'descricao' => '6661 - Devolução de compra de combustível ou lubrificante adquirido para comercialização'],
                    476 => ['id' => '6662', 'descricao' => '6662 - Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final'],
                    477 => ['id' => '6663', 'descricao' => '6663 - Remessa para armazenagem de combustível ou lubrificante'],
                    478 => ['id' => '6664', 'descricao' => '6664 - Retorno de combustível ou lubrificante recebido para armazenagem'],
                    479 => ['id' => '6665', 'descricao' => '6665 - Retorno simbólico de combustível ou lubrificante recebido para armazenagem'],
                    480 => ['id' => '6666', 'descricao' => '6666 - Remessa por conta e ordem de terceiros de ...stível ou lubrificante recebido para armazenagem'],
                    481 => ['id' => '6901', 'descricao' => '6901 - Remessa para industrialização por encomenda'],
                    482 => ['id' => '6902', 'descricao' => '6902 - Retorno de mercadoria utilizada na industrialização por encomenda'],
                    483 => ['id' => '6903', 'descricao' => '6903 - Retorno de mercadoria recebida para industrialização e não aplicada no referido processo'],
                    484 => ['id' => '6904', 'descricao' => '6904 - Remessa para venda fora do estabelecimento'],
                    485 => ['id' => '6905', 'descricao' => '6905 - Remessa para depósito fechado ou armazém geral'],
                    486 => ['id' => '6906', 'descricao' => '6906 - Retorno de mercadoria depositada em depósito fechado ou armazém geral'],
                    487 => ['id' => '6907', 'descricao' => '6907 - Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral'],
                    488 => ['id' => '6908', 'descricao' => '6908 - Remessa de bem por conta de contrato de comodato'],
                    489 => ['id' => '6909', 'descricao' => '6909 - Retorno de bem recebido por conta de contrato de comodato'],
                    490 => ['id' => '6910', 'descricao' => '6910 - Remessa em bonificação, doação ou brinde'],
                    491 => ['id' => '6911', 'descricao' => '6911 - Remessa de amostra grátis'],
                    492 => ['id' => '6912', 'descricao' => '6912 - Remessa de mercadoria ou bem para demonstração'],
                    493 => ['id' => '6913', 'descricao' => '6913 - Retorno de mercadoria ou bem recebido para demonstração'],
                    494 => ['id' => '6914', 'descricao' => '6914 - Remessa de mercadoria ou bem para exposição ou feira'],
                    495 => ['id' => '6915', 'descricao' => '6915 - Remessa de mercadoria ou bem para conserto ou reparo'],
                    496 => ['id' => '6916', 'descricao' => '6916 - Retorno de mercadoria ou bem recebido para conserto ou reparo'],
                    497 => ['id' => '6917', 'descricao' => '6917 - Remessa de mercadoria em consignação mercantil ou industrial'],
                    498 => ['id' => '6918', 'descricao' => '6918 - Devolução de mercadoria recebida em consignação mercantil ou industrial'],
                    499 => ['id' => '6919', 'descricao' => '6919 - Devolução simbólica de mercadoria vendida ...riormente em consignação mercantil ou industrial'],
                    500 => ['id' => '6920', 'descricao' => '6920 - Remessa de vasilhame ou sacaria'],
                    501 => ['id' => '6921', 'descricao' => '6921 - Devolução de vasilhame ou sacaria'],
                    502 => ['id' => '6922', 'descricao' => '6922 - Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura'],
                    503 => ['id' => '6923', 'descricao' => '6923 - Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem'],
                    504 => ['id' => '6924', 'descricao' => '6924 - Remessa para industrialização por conta e ...não transitar pelo estabelecimento do adquirente'],
                    505 => ['id' => '6925', 'descricao' => '6925 - Retorno de mercadoria recebida para indust...não transitar pelo estabelecimento do adquirente'],
                    506 => ['id' => '6929', 'descricao' => '6929 - Lançamento efetuado em decorrência de emis...ada em equipamento Emissor de Cupom Fiscal - ECF'],
                    507 => ['id' => '6931', 'descricao' => '6931 - Lançamento efetuado em decorrência da resp...nsportador autônomo ou por transportador não ins'],
                    508 => ['id' => '6932', 'descricao' => '6932 - Prestação de serviço de transporte iniciad...eração diversa daquela onde inscrito o prestador'],
                    509 => ['id' => '6933', 'descricao' => '6933 - Prestação de serviço tributado pelo ISSQN (Ajuste SINIEF 03/04)'],
                    510 => ['id' => '7101', 'descricao' => '7101 - Venda de produção do estabelecimento'],
                    511 => ['id' => '7102', 'descricao' => '7102 - Venda de mercadoria adquirida ou recebida de terceiros'],
                    512 => ['id' => '7105', 'descricao' => '7105 - Venda de produção do estabelecimento, que não deva por ele transitar'],
                    513 => ['id' => '7106', 'descricao' => '7106 - Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar'],
                    514 => ['id' => '7127', 'descricao' => '7127 - Venda de produção do estabelecimento sob o regime de "drawback"'],
                    515 => ['id' => '7201', 'descricao' => '7201 - Devolução de compra para industrialização'],
                    516 => ['id' => '7202', 'descricao' => '7202 - Devolução de compra para comercialização'],
                    517 => ['id' => '7205', 'descricao' => '7205 - Anulação de valor relativo à aquisição de serviço de comunicação'],
                    518 => ['id' => '7206', 'descricao' => '7206 - Anulação de valor relativo à aquisição de serviço de transporte'],
                    519 => ['id' => '7207', 'descricao' => '7207 - Anulação de valor relativo à compra de energia elétrica'],
                    520 => ['id' => '7210', 'descricao' => '7210 - Devolução de compra para utilização na prestação de serviço'],
                    521 => ['id' => '7211', 'descricao' => '7211 - Devolução de compras para industrialização sob o regime de "drawback"'],
                    522 => ['id' => '7301', 'descricao' => '7301 - Prestação de serviço de comunicação para execução de serviço da mesma natureza'],
                    523 => ['id' => '7358', 'descricao' => '7358 - Prestação de serviço de transporte'],
                    524 => ['id' => '7501', 'descricao' => '7501 - Exportação de mercadorias recebidas com fim específico de exportação'],
                    525 => ['id' => '7551', 'descricao' => '7551 - Venda de bem do ativo imobilizado'],
                    526 => ['id' => '7553', 'descricao' => '7553 - Devolução de compra de bem para o ativo imobilizado'],
                    527 => ['id' => '7556', 'descricao' => '7556 - Devolução de compra de material de uso ou consumo'],
                    528 => ['id' => '7651', 'descricao' => '7651 - Venda de combustível ou lubrificante de produção do estabelecimento'],
                    529 => ['id' => '7654', 'descricao' => '7654 - Venda de combustível ou lubrificante adquirido ou recebido de terceiros'],
                    530 => ['id' => '7930', 'descricao' => '7930 - Lançamento efetuado a título de devolução ...regime especial aduaneiro de admissão temporária'],
                    531 => ['id' => '7949', 'descricao' => '7949 - Outra saída de mercadoria ou prestação de serviço não especificado'],
                    532 => ['id' => '5505', 'descricao' => '5505 - Remessa de mercadorias, adquiridas ou rece...e terceiros, para formação de lote de exportação'],
                    533 => ['id' => '1128', 'descricao' => '1128 - Compra para utilização na prestação de serviço sujeita ao ISSQN.'],
                    534 => ['id' => '2128', 'descricao' => '2128 - Compra para utilização na prestação de serviço sujeita ao ISSQN.'],
                    535 => ['id' => '3128', 'descricao' => '3128 - Compra para utilização na prestação de serviço sujeita ao ISSQN'],
        ];

        $this->obterConexao()->Table('fiscalCFOP')->insert($cfops);
    }
}
